### ISSUE TITLE
Maps

### ISSUE THREAD

**Issue by ColinAE** [geanders/futureheatwaves#25]
Figure out whether to discard or keep the mapping functions. They are currently incomplete.

**Comment by geanders** [comment]
Keep. We'll need this for our paper, and others would use it for theirs, I think. I would suggest we do it this way-- have an option in `gen_hw_set` to write grid locations used for each model somewhere, but not actually map them. This should be fairly straightforward-- I think we could use `locations` to index out the lat-long values for the grid points we want from `latlong`. This will also keep you from having to integrate the actual mapping in the main `gen_hw_set` process. Then, we could write a separate function (once we have all the bugs out of the `gen_hw_set` process) to read in those points, read in the city file, and create those maps for each climate model.

**Comment by geanders** [comment]
I think we can do a fairly easy fix for this, but it will change one of your accumulators, so I didn't want to change without your advice. 

So, I'd like to change what your accumulator writes into `locationList`. Instead of what it writes now, I'd like to get it to write a small data frame for each model that we could then feed into a separate function to draw the maps (outside of the `gen_hw_set` process). I think this isn't too different from what you have going now, but I'd like to change what's in the data frame. 

I'd like `locationList` to include a data frame that looks like this for each model: 

```
 city       lat       long       alt    lat_grid    long_grid
balt    39.30080   -76.61062     20     40.464       -75.94
ny     40.66980   -73.94385      55     40.464       -73.12
nwk   40.72410   -74.17324     55     40.464       -73.12
phil   40.00682   -75.13468    100     40.464       -75.94
prov 41.82195   -71.41973       80     40.464       -70.31
```

This is just the city location dataset with two extra columns for the latitude and longitude of the closest grid points for that model. 

To create this data frame, just make sure you're somewhere in `processEnsemble` after you've run all of the following: 

```
cities <- read.csv(citycsv)
latlong <- readLatLong(ensemble)
locations <- apply(cities, 1, closest_point, latlong = latlong)
```

and add the code:

```
cities$long <- -1 * cities$long
colnames(latlong) <- c("lat_grid", "long_grid")
latlong$long_grid <- latlong$long_grid - 360
cities <- cbind(cities, latlong[locations, ])
```

Now have the location accumulator write this updated `cities` data frame for each model. With this data frame, it's pretty easy to quickly plot a nice map like we want with:

```
library(maps)  ## We'd move these to DESCRIPTION once we make this code a function
library(ggmap)
library(ggthemes)

latlong <- unique(cities[ , c("long_grid", "lat_grid")])
states <- map_data("state")
map <- ggplot()
map <- map + geom_polygon(data = states,
                          aes(x = long, y = lat, group = group),
                          colour = "lightgray", fill = "white")
map <- map + geom_point(data = latlong,
                        aes(x = long_grid, y = lat_grid),
                        color = 132, alpha = 0.6)
map <- map + geom_segment(data = cities, aes(x = long, y = lat,
                                             xend = long_grid,
                                             yend = lat_grid),
                          size = 0.9, alpha = 0.6, color = 132)
map <- map + coord_map("albers", lat0=30, lat1=40) + theme_map()
map
```

which makes a map like (this is with our reduced example dataset):

![rplot01](https://cloud.githubusercontent.com/assets/5588360/12136663/5f471434-b407-11e5-9788-c05b475135d1.png)

Each point is a grid point and then it has lines connecting it to all its closest cities. We can play with color, point size, etc. once we do this with some of the full datasets.

We can put this code into a separate mapping function that will only need as an input `cities`. Then we could apply this function to the `cities` data frames generated for each climate model to get each of the maps.

I think this would be a quick and reasonable way to get the mapping going at least to the extent we want for the paper.

**Comment by ColinAE** [comment]
Should information about which experiment,  model, and ensemble the dataframe belongs to be stored as well?

**Comment by geanders** [comment]
I don't think we need to, because the output is being saved to pathnames that give information about model and ensemble member, right? So we can figure out which output data belongs to which model based on that. Is that right?

**Comment by ColinAE** [comment]
Only the model information accumulator is being output, and only once at the end of the program's execution.

Originally, the accumulator for locations was saving the city coordinates of each ensemble so that the program could compare the entries to each other. If all of the locations were the same, it would then pass one of the dataframes contained in the list to the mapping protocol. I never actually finished the comparison behavior, however. 

Shall I have the accumulator store the information? I guess it depends on how we intend to use the location info.

**Comment by geanders** [comment]
It probably makes sense to generate this location dataframe to output when processing the Thresholds, because we only need one dataframe with locations per climate model (different ensemble members within the same climate model would have the same grid points).

**Comment by geanders** [comment]
`accumulators` now creates the dataframe I wanted to get for mapping, and `writeAccumulators` writes it out to `locationList.csv` in the `out` directory.
