### ISSUE TITLE
Acquire Directory Structure

### ISSUE THREAD

**Issue by ColinAE** [geanders/futureheatwaves#36]
Dr. Anderson,

There seems to be a problem in the acquireDirectoryStructure function. I'm a bit fatigued right now. I was wondering if you could take a look. This is the message:

Warning message:
In matrix(unlist(split_all), ncol = 4, byrow = TRUE) :
  data length [1303] is not a sub-multiple or multiple of the number of rows [326]

It's a warning, not an error, but the end result of the function is an empty list.

**Comment by geanders** [comment]
My best guess is that you might be working with a different directory structure than the sample I was working with. For this function to work, you need four levels of directories down from the dataPath directory. From there, it should be: [experiment directory]/[model directory]/[ensemble directory]/[type file (e.g., tas)]. Do you have some experiments that did not have different ensembles where you're missing the ensemble-level directory? If so, that could cause this error, I think. Check and see what the `split_all` data frame looks like for a case when you're getting this error, and if you can paste here what that looks like, I can help you figure out what's going on. It's something about what that looks like for your example that's causing this later problem, I think.

**Comment by ColinAE** [comment]
The function doesn't seem to be returning anything. I might have messed something up, though. I'll have to examine the code again.

**Comment by geanders** [comment]
If you can run your code up to where it creates the `split_all` dataframe right before this in the function and copy the output from `head(split_all)` from right before you're trying the `matrix` call, I think I could help out. I think there's something different the file structure of the files you're trying this on and the ones I'm trying this on that's causing this bug, and I should be able to see the problem if I can see what your `split_all` looks like. 

Also, I think that you should be able to get the simple example to work without a bug using the sample data in the package, because this was working fine for me and the file structure has to be the same for both of us for that example because its in the package. Try:

```
dataFolder <- "inst/cmip5/"
citycsv <- "inst/cities.csv"
```

and then run the `gen_hw_set` function with these values for `dataFolder` and `citycsv`.  If this is successful, we can be more confident that the bug has something to do with our code not being robust enough to differences in directory structure for the files you're trying and the example files.

**Comment by ColinAE** [comment]
There is definitely some kind of problem. I checked the logic of each function and it seems like each function is behaving properly. There must be a problem when stringing them together. I will have to check my earlier versions of these functions to see if the logic is consistent.

Each entry of the return value of acquireDirectoryStructure() contains the model names, but the two entries corresponding to historical and rcp85 experiments are empty.

**Comment by geanders** [comment]
Did you want to stop by sometime tomorrow with your laptop and we could check into it? I wrote that part of the code, so I could probably figure it out, but the bug's probably related to something that wasn't robust enough for other set-ups of file directories, so it would help if I could see how you have your files set up. Also, could you get it to work for you with the example data in the `inst` subdirectory of the package (see comment above for more on doing that)?

**Comment by ColinAE** [comment]
I tested it on the cmip5 data in the inst subdirectory, but it gave me the same result.

My laptop is not equipped to deal with the project. I can equip it, but it's kind of a pain. I am sure the error is something small. If I don't have it resolved by Sunday night, we should meet on Monday.

**Comment by ColinAE** [comment]
I fixed the problem. The variable ensemble_name_index was misnamed as "model_name_index" when it was being used. Interestingly enough, the interpreter did not throw an error even though model_name_index did not exist. Usually it throws an error, but there is something different about this case.

**Comment by geanders** [comment]
So, I kept running into this bug, then not, then getting it again, especially when trying to build examples and the package vignette. 

I came up with two problems going on, both of which I should have fixed now. I'm not 100% sure this won't come up again, but this should go a long way to preventing this bug in the future. 
1. The code that checks `dataFolder` to see if it ends with `/`, and adds one if not, runs in `gen_hw_set`, not in this code. That means that there's not a problem if you specify `dataFolder` without the trailing `/` in `gen_hw_set`, because one gets added before you get here, but it is a problem if you try to start from here and just test this function on its own. I've not added some code to `acquireDirectoryStructure` that does this clean-up set again at the start of `acquireDirectoryStructure`. This stops this from causing the bug. (As a note, I think we'd get the same bug if we tried to run `buildStructureExperiments` by itself with an `dataFolder` entry that lacked a trailing `/`.)
2. Related to this, to use the example data files in `inst` once you've cleared your R history built and loaded the package, you can't call directly by referring to the relative pathname `inst/cmip5`.  Instead, to pull data from an `inst` folder in a package, you need to use the call `system.file`. Here is an example of how that would work:

```
dataFolder <- system.file("cmip5", package = "futureheatwaves")
dataFolder
[1] "/Users/brookeanderson/Documents/CSU2016/cmip5heatwaves/futureheatwaves/inst/cmip5"
```

Notice that this gets the pathname fine for the files locally once a user has installed the package locally, but it does not put a trailing `/` on the pathname. That means that this example will only work okay if we are running through a function that adds a trailing slash (or we add it ourselves within the example code). For examples of how I resolved this, see the example file and code for `acquireDirectoryStructure` for an example of the first method of resolving this and the example and code for `buildStructureExperiments` for an example of the second method.
