### ISSUE TITLE
Check that the `mode` for `dir.create` calls are what we want

### ISSUE THREAD

**Issue by geanders** [geanders/futureheatwaves#56]
This is all in `IO.R`, I think.

**Comment by ColinAE** [comment]
This parameter specifies the permissions of the directory that is created with dir.create on unix-like OSes.  A value of 0777 means 'owner', 'group', and 'others' have the permission to read, write, and execute the folders. In other words, everyone has the permission to do anything they want with the file. 

Originally, specified the parameter manually since I figured I might implement the ability to customize the permissions of the output files. Otherwise, it defaults to "0777". However, the user may recursively change the permissions if they so wish, so I think we should just leave out customization of the permissions.

**Comment by geanders** [comment]
I agree that we should leave out the customization. If the default is 0777, that's fine, but let's take that argument out of the code if it's just doing the default. I don't want to do something more permissive than the default-- I think we're already going to have a bit of convincing to do to get CRAN to let us write out directories.
